package utils;

public class Paths {
	public static final String ABEOPENCURRENTACCOUNTMUDARABAHCAACSV  = "csvFiles\\ABEOpenCurrentAccountMudarabahCAA.csv";
	public static final String ABEVERIFYCURRENTACCOUNTOPENINGCSV = "csvFiles\\ABEVerifyCurrentAccountOpeningMudarabahCAA.csv";
	public static final String ABEOPENCURRENTACCOUNTMUDARABAHJSON =  "jsonFiles\\" + ABEOPENCURRENTACCOUNTMUDARABAHCAACSV.substring(9, Paths.ABEOPENCURRENTACCOUNTMUDARABAHCAACSV.length()-4) + ".json";
	public static final String ABEVERIFYCURRENTACCOUNTOPENINGJSON = "jsonFiles\\" + ABEVERIFYCURRENTACCOUNTOPENINGCSV.substring(9, Paths.ABEVERIFYCURRENTACCOUNTOPENINGCSV.length()-4) + ".json";

	public static final String ABEOPENMUDARABAHTUACSV  = "csvFiles\\ABEOpenMudarabahTUA.csv";
	public static final String ABEVERIFYMUDARABAHTUAOPENINGCSV  = "csvFiles\\ABEVerifyMudarabahTUAOpening.csv";
	public static final String ABEOPENMUDARABAHTUAJSON =  "jsonFiles\\" + ABEOPENMUDARABAHTUACSV.substring(9, Paths.ABEOPENMUDARABAHTUACSV.length()-4) + ".json";
	public static final String ABEVERIFYMUDARABAHTUAOPENINGJSON =  "jsonFiles\\" + ABEVERIFYMUDARABAHTUAOPENINGCSV.substring(9, Paths.ABEVERIFYMUDARABAHTUAOPENINGCSV.length()-4) + ".json";
	
	public static final String ABECLOSEMUDARABAHTUACSV  = "csvFiles\\ABECloseMudarabahTUA.csv";
	public static final String ABEVERIFYMUDARABAHTUACLOSURECSV  = "csvFiles\\ABEVerifyMudarabahTUAClosure.csv";
	public static final String ABECLOSEMUDARABAHTUAJSON =  "jsonFiles\\" + ABECLOSEMUDARABAHTUACSV.substring(9, Paths.ABECLOSEMUDARABAHTUACSV.length()-4) + ".json";
	public static final String ABEVERIFYMUDARABAHTUACLOSUREJSON =  "jsonFiles\\" + ABEVERIFYMUDARABAHTUACLOSURECSV.substring(9, Paths.ABEVERIFYMUDARABAHTUACLOSURECSV.length()-4) + ".json";
	
	public static final String ABEOPENWAKALAHTUACSV  = "csvFiles\\ABEOpenWakalahTUA.csv";
	public static final String ABEVERIFYWAKALAHTUAOPENINGCSV  = "csvFiles\\ABEVerifyWakalahTUAOpening.csv";
	public static final String ABEOPENWAKALAHTUAJSON =  "jsonFiles\\" + ABEOPENWAKALAHTUACSV.substring(9, Paths.ABEOPENWAKALAHTUACSV.length()-4) + ".json";
	public static final String ABEVERIFYWAKALAHTUAOPENINGJSON =  "jsonFiles\\" + ABEVERIFYWAKALAHTUAOPENINGCSV.substring(9, Paths.ABEVERIFYWAKALAHTUAOPENINGCSV.length()-4) + ".json";
	
	public static final String ABECLOSEWAKALAHTUACSV  = "csvFiles\\ABECloseWakalahTUA.csv";
	public static final String ABEVERIFYWAKALAHTUACLOSURECSV  = "csvFiles\\ABEVerifyWakalahTUAClosure.csv";
	public static final String ABECLOSEWAKALAHTUAJSON =  "jsonFiles\\" + ABECLOSEWAKALAHTUACSV.substring(9, Paths.ABECLOSEWAKALAHTUACSV.length()-4) + ".json";
	public static final String ABEVERIFYWAKALAHTUACLOSUREJSON =  "jsonFiles\\" + ABEVERIFYWAKALAHTUACLOSURECSV.substring(9, Paths.ABEVERIFYWAKALAHTUACLOSURECSV.length()-4) + ".json";
	
	public static final String ABEOPENMURABAHAACCOUNTMURABAHAFINANCINGCSV  = "csvFiles\\ABEOpenMurabahaAccountMurabahaFinancing.csv";
	public static final String ABEVERIFYMURABAHAACCOUNTOPENINGMURABAHAFINANCINGCSV  = "csvFiles\\ABEVerifyMurabahaAccountOpeningMurabahaFinancing.csv";
	public static final String ABEOPENMURABAHAACCOUNTMURABAHAFINANCINGJSON =  "jsonFiles\\" + ABEOPENMURABAHAACCOUNTMURABAHAFINANCINGCSV.substring(9, Paths.ABEOPENMURABAHAACCOUNTMURABAHAFINANCINGCSV.length()-4) + ".json";
	public static final String ABEVERIFYMURABAHAACCOUNTOPENINGMURABAHAFINANCINGJSON =  "jsonFiles\\" + ABEVERIFYMURABAHAACCOUNTOPENINGMURABAHAFINANCINGCSV.substring(9, Paths.ABEVERIFYMURABAHAACCOUNTOPENINGMURABAHAFINANCINGCSV.length()-4) + ".json";
	
	public static final String ABEDISBURSEMURABAHAACCOUNTMURABAHAFINANCINGCSV  = "csvFiles\\ABEDisburseMurabahaAccountMurabahaFinancing.csv";
	public static final String ABEVERIFYMURABAHAACCOUNTDISBURSEMENTMURABAHAFINANCINGCSV  = "csvFiles\\ABEVerifyMurabahaAccountDisbursementMurabahaFinancing.csv";
	public static final String ABEDISBURSEMURABAHAACCOUNTMURABAHAFINANCINGJSON =  "jsonFiles\\" + ABEDISBURSEMURABAHAACCOUNTMURABAHAFINANCINGCSV.substring(9, Paths.ABEDISBURSEMURABAHAACCOUNTMURABAHAFINANCINGCSV.length()-4) + ".json";
	public static final String ABEVERIFYMURABAHAACCOUNTDISBURSEMENTMURABAHAFINANCINGJSON =  "jsonFiles\\" + ABEVERIFYMURABAHAACCOUNTDISBURSEMENTMURABAHAFINANCINGCSV.substring(9, Paths.ABEVERIFYMURABAHAACCOUNTDISBURSEMENTMURABAHAFINANCINGCSV.length()-4) + ".json";
	
	public static final String ABEPAYOFFMURABAHAACCOUNTMURABAHAFINANCINGCSV  = "csvFiles\\ABEPayoffMurabahaAccountMurabahaFinancing.csv";
	public static final String ABEVERIFYMURABAHAACCOUNTPAYOFFMURABAHAFINANCINGCSV  = "csvFiles\\ABEVerifyMurabahaAccountPayoffMurabahaFinancing.csv";
	public static final String ABEPAYOFFMURABAHAACCOUNTMURABAHAFINANCINGJSON =  "jsonFiles\\" + ABEPAYOFFMURABAHAACCOUNTMURABAHAFINANCINGCSV.substring(9, Paths.ABEPAYOFFMURABAHAACCOUNTMURABAHAFINANCINGCSV.length()-4) + ".json";
	public static final String ABEVERIFYMURABAHAACCOUNTPAYOFFMURABAHAFINANCINGJSON =  "jsonFiles\\" + ABEVERIFYMURABAHAACCOUNTPAYOFFMURABAHAFINANCINGCSV.substring(9, Paths.ABEVERIFYMURABAHAACCOUNTPAYOFFMURABAHAFINANCINGCSV.length()-4) + ".json";
	
	public static final String ABEOPENCORPORATELOANCORPORATELOANSCSV  = "csvFiles\\ABEOpenCorporateLoanCorporateLoans.csv";
	public static final String ABEMODIFYCORPORATELOANCORPORATELOANSCSV  = "csvFiles\\ABEModifyCorporateLoanCorporateLoans.csv";
	public static final String ABEVERIFYCORPORATELOANCORPORATELOANSCSV  = "csvFiles\\ABEVerifyCorporateLoanCorporateLoans.csv";
	public static final String ABEOPENCORPORATELOANCORPORATELOANSJSON =  "jsonFiles\\" + ABEOPENCORPORATELOANCORPORATELOANSCSV.substring(9, Paths.ABEOPENCORPORATELOANCORPORATELOANSCSV.length()-4) + ".json";
	public static final String ABEMODIFYCORPORATELOANCORPORATELOANSJSON =  "jsonFiles\\" + ABEMODIFYCORPORATELOANCORPORATELOANSCSV.substring(9, Paths.ABEMODIFYCORPORATELOANCORPORATELOANSCSV.length()-4) + ".json";
	public static final String ABEVERIFYCORPORATELOANCORPORATELOANSJSON =  "jsonFiles\\" + ABEVERIFYCORPORATELOANCORPORATELOANSCSV.substring(9, Paths.ABEVERIFYCORPORATELOANCORPORATELOANSCSV.length()-4) + ".json";
	
	public static final String ABELODGEEXPORTBILLSTRADEFINANCECSV  = "csvFiles\\ABELodgeExportBillsTradeFinance.csv";
	public static final String ABEVERIFYLODGEEXPORTBILLSTRADEFINANCECSV  = "csvFiles\\ABEVerifyLodgeExportBillsTradeFinance.csv";
	public static final String ABELODGEEXPORTBILLSTRADEFINANCEJSON =  "jsonFiles\\" + ABELODGEEXPORTBILLSTRADEFINANCECSV.substring(9, Paths.ABELODGEEXPORTBILLSTRADEFINANCECSV.length()-4) + ".json";
	public static final String ABEVERIFYLODGEEXPORTBILLSTRADEFINANCEJSON =  "jsonFiles\\" + ABEVERIFYLODGEEXPORTBILLSTRADEFINANCECSV.substring(9, Paths.ABEVERIFYLODGEEXPORTBILLSTRADEFINANCECSV.length()-4) + ".json";
	
	public static final String ABEACCEPTEXPORTBILLSTRADEFINANCECSV  = "csvFiles\\ABEAcceptExportBillsTradeFinance.csv";
	public static final String ABEVERIFYACCEPTEXPORTBILLSTRADEFINANCECSV  = "csvFiles\\ABEVerifyAcceptExportBillsTradeFinance.csv";
	public static final String ABEACCEPTEXPORTBILLSTRADEFINANCEJSON =  "jsonFiles\\" + ABEACCEPTEXPORTBILLSTRADEFINANCECSV.substring(9, Paths.ABEACCEPTEXPORTBILLSTRADEFINANCECSV.length()-4) + ".json";
	public static final String ABEVERIFYACCEPTEXPORTBILLSTRADEFINANCEJSON =  "jsonFiles\\" + ABEVERIFYACCEPTEXPORTBILLSTRADEFINANCECSV.substring(9, Paths.ABEVERIFYACCEPTEXPORTBILLSTRADEFINANCECSV.length()-4) + ".json";
	
	public static final String ABEPURCHASEEXPORTBILLSTRADEFINANCECSV  = "csvFiles\\ABEPurchaseExportBillsTradeFinance.csv";
	public static final String ABEVERIFYPURCHASEEXPORTBILLSTRADEFINANCECSV  = "csvFiles\\ABEVerifyPurchaseExportBillsTradeFinance.csv";
	public static final String ABEPURCHASEEXPORTBILLSTRADEFINANCEJSON =  "jsonFiles\\" + ABEPURCHASEEXPORTBILLSTRADEFINANCECSV.substring(9, Paths.ABEPURCHASEEXPORTBILLSTRADEFINANCECSV.length()-4) + ".json";
	public static final String ABEVERIFYPURCHASEEXPORTBILLSTRADEFINANCEJSON =  "jsonFiles\\" + ABEVERIFYPURCHASEEXPORTBILLSTRADEFINANCECSV.substring(9, Paths.ABEVERIFYPURCHASEEXPORTBILLSTRADEFINANCECSV.length()-4) + ".json";
	
	public static final String ABEREALIZEEXPORTBILLSTRADEFINANCECSV  = "csvFiles\\ABERealizeExportBillsTradeFinance.csv";
	public static final String ABEVERIFYREALIZEEXPORTBILLSTRADEFINANCECSV  = "csvFiles\\ABEVerifyRealizeExportBillsTradeFinance.csv";
	public static final String ABEREALIZEEXPORTBILLSTRADEFINANCEJSON =  "jsonFiles\\" + ABEREALIZEEXPORTBILLSTRADEFINANCECSV.substring(9, Paths.ABEREALIZEEXPORTBILLSTRADEFINANCECSV.length()-4) + ".json";
	public static final String ABEVERIFYREALIZEEXPORTBILLSTRADEFINANCEJSON =  "jsonFiles\\" + ABEVERIFYREALIZEEXPORTBILLSTRADEFINANCECSV.substring(9, Paths.ABEVERIFYREALIZEEXPORTBILLSTRADEFINANCECSV.length()-4) + ".json";

	public static final String ABEDISBURSECORPORATELOANCORPORATELOANSCSV  = "csvFiles\\ABEDisburseCorporateLoanCorporateLoans.csv";
	public static final String ABEVERIFYCORPORATELOANDISBURSMENTCORPORATELOANSCSV  = "csvFiles\\ABEVerifyCorporateLoanDisbursmentCorporateLoans.csv";
	public static final String ABEDISBURSECORPORATELOANCORPORATELOANSJSON =  "jsonFiles\\" + ABEDISBURSECORPORATELOANCORPORATELOANSCSV.substring(9, Paths.ABEDISBURSECORPORATELOANCORPORATELOANSCSV.length()-4) + ".json";
	public static final String ABEVERIFYCORPORATELOANDISBURSMENTCORPORATELOANSJSON =  "jsonFiles\\" + ABEVERIFYCORPORATELOANDISBURSMENTCORPORATELOANSCSV.substring(9, Paths.ABEVERIFYCORPORATELOANDISBURSMENTCORPORATELOANSCSV.length()-4) + ".json";
	
	public static final String ABECREATEOFFICEACCOUNTFINANCECSV  = "csvFiles\\ABECreateOfficeAccountFinance.csv";
	public static final String ABEVERIFYOFFICEACCOUNTFINANCECSV  = "csvFiles\\ABEVerifyOfficeAccountFinance.csv";
	public static final String ABECREATEOFFICEACCOUNTFINANCEJSON =  "jsonFiles\\" + ABECREATEOFFICEACCOUNTFINANCECSV.substring(9, Paths.ABECREATEOFFICEACCOUNTFINANCECSV.length()-4) + ".json";
	public static final String ABEVERIFYOFFICEACCOUNTFINANCEJSON =  "jsonFiles\\" + ABEVERIFYOFFICEACCOUNTFINANCECSV.substring(9, Paths.ABEVERIFYOFFICEACCOUNTFINANCECSV.length()-4) + ".json";
	
	public static final String ABECREATECASACURRENTACCOUNTLIABILITIESANDOPERATIONCSV  = "csvFiles\\ABECreateCASACurrentAccountLiabilitiesAndOperation.csv";
	public static final String ABECREATECASACURRENTACCOUNTLIABILITIESANDOPERATIONJSON = "jsonFiles\\" + ABECREATECASACURRENTACCOUNTLIABILITIESANDOPERATIONCSV.substring(9, Paths.ABECREATECASACURRENTACCOUNTLIABILITIESANDOPERATIONCSV.length()-4) + ".json";
	public static final String ABEVERIFYCASACURRENTACCOUNTCREATIONLIABILITIESANDOPERATIONCSV  = "csvFiles\\ABEVerifyCasaCurrentAccountCreationLiabilitiesAndOperation.csv";
	public static final String ABEVERIFYCASACURRENTACCOUNTCREATIONLIABILITIESANDOPERATIONJSON = "jsonFiles\\" + ABEVERIFYCASACURRENTACCOUNTCREATIONLIABILITIESANDOPERATIONCSV.substring(9, Paths.ABEVERIFYCASACURRENTACCOUNTCREATIONLIABILITIESANDOPERATIONCSV.length()-4) + ".json";

	public static final String ABECREATECASASAVINGSACCOUNTLIABILITIESANDOPERATIONCSV  = "csvFiles\\ABECreateCASASavingsAccountLiabilitiesAndOperation.csv";
	public static final String ABECREATECASASAVINGSACCOUNTLIABILITIESANDOPERATIONJSON = "jsonFiles\\" + ABECREATECASASAVINGSACCOUNTLIABILITIESANDOPERATIONCSV.substring(9, Paths.ABECREATECASASAVINGSACCOUNTLIABILITIESANDOPERATIONCSV.length()-4) + ".json";
	public static final String ABEVERIFYCASASAVINGSACCOUNTCREATIONLIABILITIESANDOPERATIONCSV  = "csvFiles\\ABEVerifyCASASavingsAccountCreationLiabilitiesAndOperation.csv";
	public static final String ABEVERIFYCASASAVINGSACCOUNTCREATIONLIABILITIESANDOPERATIONJSON = "jsonFiles\\" + ABEVERIFYCASASAVINGSACCOUNTCREATIONLIABILITIESANDOPERATIONCSV.substring(9, Paths.ABEVERIFYCASASAVINGSACCOUNTCREATIONLIABILITIESANDOPERATIONCSV.length()-4) + ".json";
	
	public static final String ABETELLEROPERATIONTRANSFERLIABILITIESANDOPERATIONCSV  = "csvFiles\\ABETellerOperationTransferLiabilitiesAndOperation.csv";
	public static final String ABETELLEROPERATIONTRANSFERLIABILITIESANDOPERATIONJSON =  "jsonFiles\\" + ABETELLEROPERATIONTRANSFERLIABILITIESANDOPERATIONCSV.substring(9, Paths.ABETELLEROPERATIONTRANSFERLIABILITIESANDOPERATIONCSV.length()-4) + ".json";
	
	public static final String ABECREATETDLIABILITIESANDOPERATIONCSV  = "csvFiles\\ABECreateTdLiabilitiesAndOperation.csv";
	public static final String ABECREATETDLIABILITIESANDOPERATIONJSON =  "jsonFiles\\" + ABECREATETDLIABILITIESANDOPERATIONCSV.substring(9, Paths.ABECREATETDLIABILITIESANDOPERATIONCSV.length()-4) + ".json";

	public static final String ABEVERIFYTDLIABILITIESANDOPERATIONCSV  = "csvFiles\\ABEVerifyTDLiabilities&Operation.csv";
	public static final String ABEVERIFYTDLIABILITIESANDOPERATIONJSON =  "jsonFiles\\" + ABEVERIFYTDLIABILITIESANDOPERATIONCSV.substring(9, Paths.ABEVERIFYTDLIABILITIESANDOPERATIONCSV.length()-4) + ".json";

	public static final String ABEOPENRETAILLOANRETAILLOANSCSV  = "csvFiles\\ABEOpenRetailLoanRetailLoans.csv";
	public static final String ABEOPENRETAILLOANRETAILLOANSJSON =  "jsonFiles\\" + ABEOPENRETAILLOANRETAILLOANSCSV.substring(9, Paths.ABEOPENRETAILLOANRETAILLOANSCSV.length()-4) + ".json";

	public static final String ABEVERIFYRETAILLOANRETAILLOANSCSV  = "csvFiles\\ABEVerifyRetailLoanRetailLoans.csv";
	public static final String ABEVERIFYRETAILLOANRETAILLOANSJSON =  "jsonFiles\\" + ABEVERIFYRETAILLOANRETAILLOANSCSV.substring(9, Paths.ABEVERIFYRETAILLOANRETAILLOANSCSV.length()-4) + ".json";

	public static final String ABEDISBURSERETAILLOANRETAILLOANSCSV  = "csvFiles\\ABEDisburseRetailLoanRetailLoans.csv";
	public static final String ABEDISBURSERETAILLOANRETAILLOANSJSON =  "jsonFiles\\" + ABEDISBURSERETAILLOANRETAILLOANSCSV.substring(9, Paths.ABEDISBURSERETAILLOANRETAILLOANSCSV.length()-4) + ".json";

	public static final String ABEVERIFYRETAILLOANDISBURSMENTRETAILLOANSCSV  = "csvFiles\\ABEVerifyRetailLoanDisbursmentRetailLoans.csv";
	public static final String ABEVERIFYRETAILLOANDISBURSMENTRETAILLOANSJSON =  "jsonFiles\\" + ABEVERIFYRETAILLOANDISBURSMENTRETAILLOANSCSV.substring(9, Paths.ABEVERIFYRETAILLOANDISBURSMENTRETAILLOANSCSV.length()-4) + ".json";

}